baseurl = "/"

title = "Nicole Schafer Photo & Film"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration   
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

enableEmoji = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.de]
    languageName = "DE"
    [[languages.de.menu.main]]
        name = "Startseite"
        url = "/"
    [[languages.de.menu.main]]
        name = "Dienstleistungen"
        url = "/service"
    [[languages.de.menu.main]]
        name = "Blog"
        url = "/post"
    [[languages.de.menu.main]]
        name = "Kontakt"
        url = "/contact"
  [languages.en]
    languageName = "EN"
    [[languages.en.menu.main]]
        name = "Home"
        url = "/"
    [[languages.en.menu.main]]
        name = "Services"
        url = "/service"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "/post"
    [[languages.en.menu.main]]
        name = "Contact"
        url = "/contact"