backend:
  name: github
  repo: dr-useless/nsphoto2
  base_url: https://nsphoto-github-oauth.dr-useless.workers.dev
  branch: cloudflare-kv-media-store # TODO: revert to master

media_folder: "site/static/media" # Folder where user uploaded files should go
public_folder: media

locale: en
i18n:
  structure: multiple_files
  locales: [en, de]
  default_locale: en

collections: # A list of collections the CMS should be able to edit
  - name: post # Used in routes, ie.: /admin/collections/:slug/edit
    label: Post # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    public_folder: "en/post/{{slug}}"
    i18n: true
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: "Publish Date", name: date, widget: datetime , i18n: duplicate}
      - {label: "Intro Blurb", name: description, widget: text, i18n: true}
      - {label: "Featured Image", name: featured_image, widget: nsp-image, required: false, max_width: 750, i18n: duplicate}
      - {label: Body, name: body, widget: markdown, i18n: true}
  - name: "album"
    label: "Album"
    folder: "site/content/album"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: "en/album/{{slug}}"
    i18n: true
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: "Publish Date", name: date, widget: datetime, i18n: duplicate}
      - {label: Description, name: description, widget: text, i18n: true}
      - {label: "Tags", name: "tags", widget: list, max: 5, i18n: true}
      - {label: "Featured Image", name: featured_image, widget: nsp-image, max_width: 750, i18n: duplicate}
      - {label: Images, name: images, widget: nsp-image-list, max_width: 750, i18n: duplicate}
      - {label: Videos, name: videos, widget: list, i18n: true, add_to_top: true, required: false,
          field: {label: "YouTube Video ID", name: youtube_id, widget: string, i18n: true}
        }
  - name: "film"
    label: "Film"
    folder: "site/content/film"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: "en/film/{{slug}}"
    i18n: true
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: "Publish Date", name: date, widget: datetime, i18n: true}
      - {label: Description, name: description, widget: text, i18n: true}
      - {label: "Tags", name: "tags", widget: list, max: 5, i18n: true}
      - {label: "Featured Image", name: featured_image, widget: nsp-image, max_width: 750, i18n: duplicate, required: false}
      - {label: "YouTube Video ID", name: youtube_id, widget: string, i18n: duplicate}
  - name: "service"
    label: "Service"
    folder: "site/content/service"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: "en/service/{{slug}}"
    i18n: true
    create: true
    fields:
      - {label: Title, name: title, widget: string, i18n: true}
      - {label: Description, name: description, widget: text, i18n: true}
      - {label: "Featured Image", name: featured_image, widget: nsp-image, max_width: 750, i18n: duplicate, required: false}
      - {label: Body, name: body, widget: markdown, required: false, i18n: true}
      - {label: "Packages", name: "packages", widget: list, i18n: true, fields: [
          {label: Name, name: "name", widget: string, i18n: true},
          {label: Description, name: description, widget: text, i18n: true},
          {label: Features, name: features, widget: list, i18n: true, fields: [
            {label: Name, name: "name", widget: string, i18n: true},
            {label: Description, name: description, widget: text, i18n: true}
          ]},
          {label: Price, name: price, widget: number, value_type: int, min: 0, step: 1, default: 100, i18n: duplicate}
        ]}
  - name: pages
    label: Pages
    files:
      - file: "site/content/_index.en.md"
        name: home_en
        label: "Home EN"
        media_folder: ""
        public_folder: "en"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: "Featured Image", name: featured_image, widget: nsp-image, max_width: 1600}
          - {label: "Select Clients", name: clients, widget: nsp-image-list, max_width: 120}
      - file: "site/content/_index.de.md"
        name: home_de
        label: "Home DE"
        path: "home"
        media_folder: ""
        public_folder: "en"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: "Featured Image", name: featured_image, widget: nsp-image, max_width: 1600}
          - {label: "Select Clients", name: clients, widget: nsp-image-list, max_width: 120}
      - file: "site/content/contact/_index.en.md"
        name: contact_en
        label: "Contact EN"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Success Message", name: success_message, widget: text}
      - file: "site/content/contact/_index.de.md"
        name: contact_de
        label: "Contact DE"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Success Message", name: success_message, widget: text}
      - file: "site/content/privacy/_index.en.md"
        name: privacy_en
        label: "Privacy Policy EN"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/privacy/_index.de.md"
        name: privacy_de
        label: "Privacy Policy DE"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}