name = "nsphoto-media-store"
type = "javascript"
account_id = "b7554562ae5b04f46e2b9efa3e565d72"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "MEDIA", id = "ca5d24db13f9460f970da35332b3315a", preview_id = "08680b754f5641a7916548a805789667" }
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"